/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop.b.sepuluh;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        FifteenPuzzle classUnderTest = new FifteenPuzzle();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
